import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import { List, Item } from '../types';

export const exportToPDF = async (list: List, items: Item[]) => {
    const htmlContent = `
    <!DOCTYPE html>
    <html>
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <style>
          body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
            padding: 20px;
            color: #111827;
          }
          .header {
            text-align: center;
            margin-bottom: 30px;
            padding-bottom: 20px;
            border-bottom: 3px solid ${list.color};
          }
          .icon {
            font-size: 48px;
            margin-bottom: 10px;
          }
          h1 {
            margin: 10px 0;
            color: #111827;
            font-size: 32px;
          }
          .meta {
            color: #6b7280;
            font-size: 14px;
          }
          .item {
            background: #f9fafb;
            border-left: 4px solid ${list.color};
            padding: 15px;
            margin-bottom: 20px;
            border-radius: 8px;
          }
          .field {
            margin-bottom: 10px;
          }
          .field-label {
            font-size: 11px;
            font-weight: 600;
            color: #6b7280;
            text-transform: uppercase;
            margin-bottom: 4px;
          }
          .field-value {
            font-size: 16px;
            color: #111827;
          }
          .field-empty {
            font-size: 16px;
            color: #d1d5db;
            font-style: italic;
          }
          .footer {
            margin-top: 40px;
            padding-top: 20px;
            border-top: 1px solid #e5e7eb;
            text-align: center;
            color: #9ca3af;
            font-size: 12px;
          }
        </style>
      </head>
      <body>
        <div class="header">
          <div class="icon">${list.icon}</div>
          <h1>${list.name}</h1>
          <p class="meta">${items.length} item${items.length !== 1 ? 's' : ''} • Exported on ${new Date().toLocaleDateString()}</p>
        </div>
        
        ${items.map((item, index) => `
          <div class="item">
            ${list.schema.fields.map(field => {
        const value = item.data[field.name];
        let displayValue = '—';

        if (value !== null && value !== undefined && value !== '') {
            if (field.type === 'boolean') {
                displayValue = value ? 'Yes' : 'No';
            } else if (field.type === 'date') {
                displayValue = new Date(value).toLocaleDateString();
            } else {
                displayValue = String(value);
            }
        }

        return `
                <div class="field">
                  <div class="field-label">${field.name}</div>
                  <div class="${value !== null && value !== undefined && value !== '' ? 'field-value' : 'field-empty'}">
                    ${displayValue}
                  </div>
                </div>
              `;
    }).join('')}
          </div>
        `).join('')}
        
        <div class="footer">
          Generated by DataNest
        </div>
      </body>
    </html>
  `;

    try {
        const { uri } = await Print.printToFileAsync({ html: htmlContent });
        await Sharing.shareAsync(uri, { UTI: '.pdf', mimeType: 'application/pdf' });
    } catch (error) {
        console.error('Error generating PDF:', error);
        throw error;
    }
};